env:
    credentials: "ENCRYPTED[c3687dc1b9eb728dba684ff5666da8505f469dafeae536c23c381e9f796dd4aa3cbd47273f421150633b46d852df8099]"
    rcloneconfig: "ENCRYPTED[0aee56489b34fd192aaf78215f034690be69bae84124a8fc7b095501d683ed60e2c86ac6b96d6ed4271c366d86a2de19]"
    tokentl: "ENCRYPTED[c179af28bfa836268495c4e358ef6eea19431c513c19fd6ea5e3e48fe12606eb639ff87c32e7e8ce499a2ac1bf9d561c]"
    idtl: "ENCRYPTED[109c253143eb4f627084fb1d47bba6b76ed1c7be94eb6a784b9f2f36dc1e4d72fa3a05d6190fef55ba69db5081bf883b]"
    lunch: lunch nad_juice-userdebug
    make: make nad

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 120m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Setup Build"
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - git config --global user.name "maung-bodaz"
       - git config --global user.email "maung.bodazzzz@gmail.com"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p /tmp/ccache
       - rclone copy NFS:nusantara/ccache.tar.gz /tmp -P
       - cd /tmp
       - time tar xf ccache.tar.gz
       - cd /tmp
  
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync Source"
      - cd /tmp/rom
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/NusantaraProject-ROM/android_manifest -b 11 -g default,-device,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      # DT/VT/KT/TC
      - git clone --depth=1 https://github.com/I-n-o-k/device_xiaomi_juice -b nusantara device/xiaomi/juice
      - git clone --depth=1 https://gitlab.com/I-n-o-k/vendor-lime --single-branch -b 11 vendor/xiaomi/juice
      - git clone --depth=1 https://github.com/I-n-o-k/android_kernel_xiaomi_bengal --single-branch -b 11.0 kernel/xiaomi/juice
      # HALS
      - rm -rf hardware/qcom-caf/sm8250/audio
      - rm -rf hardware/qcom-caf/sm8250/display
      - rm -rf hardware/qcom-caf/sm8250/media
      - rm -rf external/json-c
      - rm -rf hardware/xiaomi
      - git clone --depth=1 https://github.com/LineageOS/android_hardware_xiaomi hardware/xiaomi
      - git clone --depth=1 https://github.com/I-n-o-k/hardware_qcom-caf_sm8250_audio hardware/qcom-caf/sm8250/audio
      - git clone --depth=1 https://github.com/I-n-o-k/hardware_qcom-caf_sm8250_display hardware/qcom-caf/sm8250/display
      - git clone --depth=1 https://github.com/I-n-o-k/hardware_qcom-caf_sm8250_media hardware/qcom-caf/sm8250/media
      - git clone --depth=1 https://github.com/LineageOS/android_external_json-c -b lineage-18.1 external/json-c
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

      - echo "============================"
      - echo "Sync Completed!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - ./collect.sh
      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/juice/ && ls Nusantara*.zip) Completed!"
      - echo "============================"
      - echo "Build Completed!"
      - echo "============================"

  Upload_script:
      - echo "============================"
      - echo "Uploading the Build...."
      - echo "============================"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading Build $(cd /tmp/rom/out/target/product/juice/ && ls Nusantara*.zip)"
      - rclone copy /tmp/rom/out/target/product/juice/Nusantara*.zip NFS:juice -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/juice/ && ls Nusantara*.zip) Uploaded Successfully!"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Download link http://anu.inok189.workers.dev/juice/$(cd /tmp/rom/out/target/product/juice/ && ls Nusantara*.zip)"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd /tmp
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz inok:nusantara -P
      - echo " "
      - echo "============================"
      - echo "Build Uploaded Successfully!"
      - echo "============================"

